name: Build-Apk

on:
  workflow_dispatch:

  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - run: chmod 777 ./gradlew
      - run: ./gradlew app:assemble

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk
